export const FETCH_COIN_DETAILS = "FETCH_COIN_DETAILS";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE";
export const FETCH_COIN_HISTORY = "FETCH_COIN_HISTORY";
export const FETCH_COIN_HISTORY_SUCCESS = "FETCH_COIN_HISTORY_SUCCESS";
export const FETCH_COIN_HISTORY_FAILURE = "FETCH_COIN_HISTORY_FAILURE";
export const SET_CHART_FILTERS = "SET_CHART_FILTERS";
export const FETCH_TRENDING_COIN = "FETCH_TRENDING_COIN";
export const FETCH_TRENDING_COINS_FAILURE = "FETCH_TRENDING_COINS_FAILURE";
export const FETCH_TRENDING_COINS_SUCCESS = "FETCH_TRENDING_COINS_SUCCESS";

export const ADD_TO_WATCH_LISTS = "ADD_TO_WATCH_LISTS";
